# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/identite.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IdCard(object):
    def setupUi(self, IdCard):
        IdCard.setObjectName("IdCard")
        IdCard.resize(800, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../assets/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IdCard.setWindowIcon(icon)
        IdCard.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(IdCard)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 761, 251))
        self.label.setStyleSheet("border-bottom: 2px solid black;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/../assets/angel.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 170, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.iPrenom = QtWidgets.QLabel(self.centralwidget)
        self.iPrenom.setGeometry(QtCore.QRect(300, 150, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iPrenom.setFont(font)
        self.iPrenom.setScaledContents(False)
        self.iPrenom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iPrenom.setObjectName("iPrenom")
        self.iNom = QtWidgets.QLabel(self.centralwidget)
        self.iNom.setGeometry(QtCore.QRect(300, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iNom.setFont(font)
        self.iNom.setStyleSheet("border-bottom: 2px dashed black;\n"
"")
        self.iNom.setScaledContents(False)
        self.iNom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iNom.setObjectName("iNom")
        self.iSexe = QtWidgets.QLabel(self.centralwidget)
        self.iSexe.setGeometry(QtCore.QRect(300, 210, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iSexe.setFont(font)
        self.iSexe.setScaledContents(False)
        self.iSexe.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iSexe.setObjectName("iSexe")
        self.iBirthPlace = QtWidgets.QLabel(self.centralwidget)
        self.iBirthPlace.setGeometry(QtCore.QRect(300, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iBirthPlace.setFont(font)
        self.iBirthPlace.setScaledContents(False)
        self.iBirthPlace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iBirthPlace.setObjectName("iBirthPlace")
        self.iPhone = QtWidgets.QLabel(self.centralwidget)
        self.iPhone.setGeometry(QtCore.QRect(300, 280, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iPhone.setFont(font)
        self.iPhone.setScaledContents(False)
        self.iPhone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iPhone.setObjectName("iPhone")
        self.iBirthDay = QtWidgets.QLabel(self.centralwidget)
        self.iBirthDay.setGeometry(QtCore.QRect(300, 170, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iBirthDay.setFont(font)
        self.iBirthDay.setScaledContents(False)
        self.iBirthDay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iBirthDay.setObjectName("iBirthDay")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(290, 10, 241, 61))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 10, 101, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("ui/../assets/nigeria.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.iPhoto = QtWidgets.QLabel(self.centralwidget)
        self.iPhoto.setGeometry(QtCore.QRect(530, 120, 161, 181))
        self.iPhoto.setText("")
        self.iPhoto.setPixmap(QtGui.QPixmap("ui/../assets/pngwing.com (1).png"))
        self.iPhoto.setScaledContents(True)
        self.iPhoto.setObjectName("iPhoto")
        self.capture = QtWidgets.QPushButton(self.centralwidget)
        self.capture.setGeometry(QtCore.QRect(370, 360, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.capture.setFont(font)
        self.capture.setStyleSheet("background:rgb(148, 123, 200);\n"
"color:#fff;\n"
"border:none;\n"
"border-radius:5px")
        self.capture.setObjectName("capture")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 10, 101, 61))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("ui/../assets/amoirie.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        IdCard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IdCard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        IdCard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IdCard)
        self.statusbar.setObjectName("statusbar")
        IdCard.setStatusBar(self.statusbar)

        self.retranslateUi(IdCard)
        QtCore.QMetaObject.connectSlotsByName(IdCard)

    def retranslateUi(self, IdCard):
        _translate = QtCore.QCoreApplication.translate
        IdCard.setWindowTitle(_translate("IdCard", "Carte Idenité"))
        self.label_3.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Nom  :</p></body></html>"))
        self.label_4.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Prenom :</p></body></html>"))
        self.label_5.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Date de Naissance :</p></body></html>"))
        self.label_6.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Sexe :</p></body></html>"))
        self.label_7.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Lieu de Naissance :</p></body></html>"))
        self.label_8.setText(_translate("IdCard", "<html><head/><body><p align=\"right\">Telephone :</p></body></html>"))
        self.iPrenom.setText(_translate("IdCard", "Ridwan"))
        self.iNom.setText(_translate("IdCard", "<html><head/><body><p>Azeez</p></body></html>"))
        self.iSexe.setText(_translate("IdCard", "H"))
        self.iBirthPlace.setText(_translate("IdCard", "Abobo"))
        self.iPhone.setText(_translate("IdCard", "07-897-734-20"))
        self.iBirthDay.setText(_translate("IdCard", "20/07/00"))
        self.label_9.setText(_translate("IdCard", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Carte</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">d\'Identité</span></p></body></html>"))
        self.capture.setText(_translate("IdCard", "Capture"))
import ressource_rc
